version: 0.0
os: linux
files:
   - source: /myapp
     destination: /home/ec2-user/myapp
     
permissions:
   - object: /home/ec2-user/myapp
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   AfterInstall:
    - location: scripts/install-packages.sh